### PR TITLE
Ensure the release container does not contain any unintended files

### LINKED ISSUE #1769: [BUG]: Release container potentially includes unneeded files
### Version

24.06

### Which installation method(s) does this occur on?

Docker

### Describe the bug.

Because we copy files from the host's repo with:
```
COPY "${MORPHEUS_ROOT_HOST}/docs" "./docs"
COPY "${MORPHEUS_ROOT_HOST}/examples" "./examples"
```
Which could potentially include intermediate `build` dirs, `*.so` files, and intermediate files from the documentation builds

We should probably consider performing a `git clone` from within the container.

### Minimum reproducible example

Build locally in a conda env or in a development container
Build the release container

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

 [Paste the error here, it will be hidden by default]

</pre></details>

### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>

### Other/Misc.

_No response_

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

### PR DESCRIPTION
**Pull request by dagardner-nv**
## Description
* Rather than copy directly from the host's repo, perform a `git clone` ensuring that any local build artifacts or uncommitted changes don't find their way into the release image.

Closes #1769

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

### CODE REVIEW

File: docker/Dockerfile [hunk 1]
```diff
@@ -251,21 +292,37 @@ RUN --mount=type=bind,from=conda_bld_morpheus,source=/opt/conda/conda-bld,target
...
+ARG GIT_URL
+ARG GIT_BRANCH
+ARG GIT_COMMIT
+
+RUN source activate morpheus &&\
+    git clone --branch ${GIT_BRANCH} ${GIT_URL} /tmp/morpheus_repo &&\
+    cd /tmp/morpheus_repo &&\
+    git checkout ${GIT_COMMIT} &&\
+    git lfs install &&\
+    /tmp/morpheus_repo/scripts/fetch_data.py fetch examples models
```
Comment (mdemoret-nv) [inline docker/Dockerfile:309]: This seems like it could be improved by doing something similar to what conda does and clone from a local git repo. This would avoid needing to specify the URL, branch and commit. It would just use whatever is currently cloned.

Should be something like `git clone file:///path/to/repo.git/`

File: docker/build_container_release.sh [hunk 2]
```diff
@@ -24,10 +24,14 @@ export DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME:-"nvcr.io/nvidia/morpheus/morpheus"
 export DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG:-"$(git describe --tags --abbrev=0)-runtime"}
 export DOCKER_TARGET=${DOCKER_TARGET:-"runtime"}
 
-popd &> /dev/null
+export GIT_URL=${GIT_URL:-$(git remote get-url origin)}
```
Comment (mdemoret-nv) [inline docker/build_container_release.sh:27]: This seems problematic based on the name of the remote and would be improved with a local clone

File: docker/Dockerfile (hunk 1 above)
Comment (mdemoret-nv) [inline docker/Dockerfile:309]: Do we need models anymore?

**Review by mdemoret-nv — CHANGES_REQUESTED** [review]
Good improvement but I think this could be simplified a bit with a local clone from another director

File: docker/Dockerfile (hunk 1 above)
Comment (dagardner-nv) [reply docker/Dockerfile:309]: No, so long as we assume that #1804 is merged

**Review by mdemoret-nv — APPROVED** [review]
