### PR TITLE
Fix pathlib.Path support for FileSourceStage

### LINKED ISSUE #1530: [BUG]: Using pathlib.Path for the filename parameter for FileSourceStage breaks file type inference
### Version

24.03

### Which installation method(s) does this occur on?

Source

### Describe the bug.

`FileSourceStage` uses `pathlib.Path` as the type-hint for the `filename` argument, but the `determine_file_type` function requires a string.

### Minimum reproducible example

```shell
diff --git a/tests/test_file_in_out.py b/tests/test_file_in_out.py
index 7100aea5..d698c3a4 100755
--- a/tests/test_file_in_out.py
+++ b/tests/test_file_in_out.py
@@ -16,6 +16,7 @@
 
 import filecmp
 import os
+import pathlib
 
 import numpy as np
 import pytest
@@ -39,11 +40,16 @@ from morpheus.stages.preprocess.deserialize_stage import DeserializeStage
 
 @pytest.mark.slow
 @pytest.mark.parametrize("input_type", ["csv", "jsonlines", "parquet"])
+@pytest.mark.parametrize("use_pathlib", [False, True])
 @pytest.mark.parametrize("output_type", ["csv", "json", "jsonlines"])
 @pytest.mark.parametrize("flush", [False, True], ids=["no_flush", "flush"])
 @pytest.mark.parametrize("repeat", [1, 2, 5], ids=["repeat1", "repeat2", "repeat5"])
-def test_file_rw_pipe(tmp_path, config, input_type, output_type, flush, repeat: int):
+def test_file_rw_pipe(tmp_path, config, input_type, use_pathlib: bool, output_type, flush, repeat: int):
     input_file = os.path.join(TEST_DIRS.tests_data_dir, f'filter_probs.{input_type}')
+
+    if use_pathlib:
+        input_file = pathlib.Path(input_file)
+
```
```


### Relevant log output

<details><summary>Click here to see error details</summary><pre>

 [Paste the error here, it will be hidden by default]

</pre></details>


### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>


### Other/Misc.

_No response_

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

### PR DESCRIPTION
**Pull request by dagardner-nv**
## Description
* The type hint for the `filename` argument to the `FileSourceStage` is `pathlib.Path`, however this is incompatible with the C++ impl and the `determine_file_type` method.
Closes #1530

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

### CODE REVIEW

File: morpheus/_lib/stages/module.cpp [hunk 1]
```diff
@@ -107,11 +112,21 @@ PYBIND11_MODULE(stages, _module)
              py::arg("task_type")              = py::none(),
              py::arg("task_payload")           = py::none());
 
+    // py::overload_cast<const std::filesystem::path&>
```
Comment (mdemoret-nv) [inline morpheus/_lib/stages/module.cpp:115]: extra comment

**Review by mdemoret-nv — APPROVED** [review]
