### PR TITLE
Several fixes & improvements of C++ `MonitorStage`

### LINKED ISSUE #2148: [BUG]: MonitorStage ensure at least one log line
### Version

25.02

### Which installation method(s) does this occur on?

Source, Docker

### Describe the bug.

For short-running pipelines, the monitor stage will potentially not emit any output. 
We should always get the final `Complete` message which contains the total message count along with the message rate.

### Minimum reproducible example

```shell
Any short-running pipeline will do, in testing this one will reproduce the error if you run it enough time

morpheus --log_level=debug --plugin examples/developer_guide/1_simple_python_stage/pass_thru.py \
  run pipeline-other \
  from-file --filename=examples/data/email_with_addresses.jsonlines \
  pass-thru \
  monitor


Compare with:

morpheus --log_level=debug --plugin examples/developer_guide/1_simple_python_stage/pass_thru.py \
  run --use_cpu_only pipeline-other \
  from-file --filename=examples/data/email_with_addresses.jsonlines \
  pass-thru \
  monitor
```

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

```
Configuring Pipeline via CLI
====Pipeline Pre-build====
====Pre-Building Segment: linear_segment_0====
====Pre-Building Segment Complete!====
====Pipeline Pre-build Complete!====
====Registering Pipeline====
Starting pipeline via CLI... Ctrl+C to Quit
====Building Pipeline====
====Building Pipeline Complete!====
====Registering Pipeline Complete!====
Config: 
{
  "_model_max_batch_size": 8,
  "_pipeline_batch_size": 256,
  "ae": null,
  "class_labels": [],
  "debug": false,
  "edge_buffer_size": 128,
  "execution_mode": "GPU",
  "feature_length": 1,
  "fil": {
    "feature_columns": null
  },
  "frozen": true,
  "log_config_file": null,
  "log_level": 10,
  "mode": "OTHER",
  "num_threads": 64,
  "plugins": [
    "examples/developer_guide/1_simple_python_stage/pass_thru.py"
  ]
}
CPP Enabled: True
====Starting Pipeline====
====Pipeline Started====
====Building Segment: linear_segment_0====
Added source: <from-file-0; FileSourceStage(filename=examples/data/email_with_addresses.jsonlines, iterative=False, file_type=FileTypes.Auto, repeat=1, filter_null=True, filter_null_columns=(), parser_kwargs={})>
  └─> morpheus.MessageMeta
Added stage: <pass-thru-1; PassThruStage()>
  └─ morpheus.MessageMeta -> morpheus.MessageMeta
Added stage: <monitor-2; MonitorStage(description=Progress, smoothing=0.05, unit=messages, delayed_start=True, determine_count_fn=None, text_color=IndicatorsTextColor.cyan, font_style=IndicatorsFontStyle.bold, log_level=LogLevels.INFO)>
  └─ morpheus.MessageMeta -> morpheus.MessageMeta
====Building Segment Complete!====

====Pipeline Complete====
```

</pre></details>

### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>

### Other/Misc.

_No response_

### Code of Conduct

- [x] I agree to follow Morpheus' Code of Conduct
- [x] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

### PR DESCRIPTION
**Pull request by yczhang-nv**
## Description

- For some short-running pipelines, `MonitorStage` now ensures there's at least one line of progress bar output with throughput shown.
- For pipelines need explicitly stopped with `Ctrl+C`, `MonitorStage` now ensures to output the progress bars again when the pipeline is completed, avoids the progress bars from being covered by other logs.
- Using `microseconds` when calculating the throughput to avoid `inf` throughput
- Each completed progress bar will turn into green with text `[Completed]`

Closes #2148

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

### CODE REVIEW

File: python/morpheus/morpheus/_lib/include/morpheus/controllers/monitor_controller.hpp [hunk 1]
```diff
@@ -314,11 +330,11 @@ std::string MonitorController<MessageT>::format_duration(std::chrono::seconds du
 }
 
 template <typename MessageT>
-std::string MonitorController<MessageT>::format_throughput(std::chrono::seconds duration,
+std::string MonitorController<MessageT>::format_throughput(std::chrono::microseconds duration,
                                                            size_t count,
                                                            const std::string& unit)
 {
-    double throughput = static_cast<double>(count) / duration.count();
+    double throughput = static_cast<double>(count) / duration.count() * 1000 * 1000;
```
Comment (willkill07) [inline python/morpheus/morpheus/_lib/include/morpheus/controllers/monitor_controller.hpp:337]: Just a small nit to avoid magic numbers with microseconds.

This also potentially makes it more accurate since there is only one operation (division). The internal ratio scaling of `chrono::duration` + `chrono::duration_cast` is really good.

```suggestion
    double time_in_seconds = std::chrono::duration_cast<std::chrono::duration<double>>(duration).count();
    double throughput = static_cast<double>(count) / time_in_seconds;
```

File: python/morpheus/morpheus/_lib/include/morpheus/controllers/monitor_controller.hpp [hunk 2]
```diff
@@ -298,14 +309,19 @@ template <typename MessageT>
...
     manager.mark_pbar_as_completed(m_bar_id);
 }
 
 template <typename MessageT>
-std::string MonitorController<MessageT>::format_duration(std::chrono::seconds duration)
+std::string MonitorController<MessageT>::format_duration(std::chrono::microseconds duration)
 {
     auto minutes = std::chrono::duration_cast<std::chrono::minutes>(duration);
-    auto seconds = duration - minutes;
+    auto seconds = std::chrono::duration_cast<std::chrono::seconds>(duration - minutes);
```
Comment (willkill07) [inline python/morpheus/morpheus/_lib/include/morpheus/controllers/monitor_controller.hpp:324]: Question: do you want this to be truncated to the nearest whole number or would you want to present anything with sub-second granularity?

**Review by willkill07 — COMMENTED** [review]
Just some minor feedback + suggestions. Nothing that should block the PR.

File: python/morpheus/morpheus/_lib/include/morpheus/controllers/monitor_controller.hpp (hunk 1 above)
Comment (yczhang-nv) [reply python/morpheus/morpheus/_lib/include/morpheus/controllers/monitor_controller.hpp]: Love this. Thanks!

File: python/morpheus/morpheus/_lib/include/morpheus/controllers/monitor_controller.hpp (hunk 2 above)
Comment (yczhang-nv) [reply python/morpheus/morpheus/_lib/include/morpheus/controllers/monitor_controller.hpp:333]: Rounded to the nearest whole number should be enough for current use cases.

**Review by willkill07 — APPROVED** [review]
