### PR TITLE
Fix C++ version of `MonitorStage` output issue caused by out of order function calls

### LINKED ISSUE #2119: [BUG]: C++ impl of monitor stage doesn't reset the cursor on shutdown
### Version

25.02

### Which installation method(s) does this occur on?

Source

### Describe the bug.

On shutdown of a pipeline using multiple monitor stages, the cursor will be left in the middle of the output.

This causes the shell prompt to overwrite a portion of the output, and the shell prompt might not be visible to the end-user.

### Minimum reproducible example

```shell
Run the `examples/abp_pcap_detection` example as documented.
```

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

====Building Segment Complete!====
Preprocessing rate[      #   ] 537241 messages in 00m:09s, Throughput: 59693.44 messages/s                                                                    
(morpheus) dagardner@roci:~/work/morpheus$ m:09s, Throughput: 59693.44 inf/s                                                                                  
Add classification rate[      #   ] 537241 add-class in 00m:09s, Throughput: 59693.44 add-class/s                                                             
Serialize rate[      #   ] 537241 ser in 00m:09s, Throughput: 59693.44 ser/s                                                                                  
Write to file rate[      #   ] 537241 to-file in 00m:09s, Throughput: 59693.44 to-file/s                                                                      
====Pipeline Complete====

</pre></details>

### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>

### Other/Misc.

_No response_

### Code of Conduct

- [x] I agree to follow Morpheus' Code of Conduct
- [x] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

### PR DESCRIPTION
**Pull request by yczhang-nv**
## Description

image

- [#2121](https://github.com/nv-morpheus/Morpheus/pull/2121) ensures the cursor is reset to the last line of output after shutdown by adding `ProgressBarContextManager::mark_pbar_as_completed()`. 
- When executing some of the pipelines, race conditions may cause calling `ProgressBarContextManager::display_all()` after `ProgressBarContextManager::mark_pbar_as_completed()`, which intermittently causes the log display issue above - which should has been fixed by this PR.

Closes #2119 

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

### CODE REVIEW

File: python/morpheus/morpheus/_lib/include/morpheus/controllers/monitor_controller.hpp [hunk 1]
```diff
@@ -114,11 +120,11 @@ class ProgressBarContextManager
         {
             pbar->print_progress(true);
             m_stdout_os << termcolor::reset;  // The font option only works for the current bar
-            m_stdout_os << "\n";
+            m_stdout_os << "\n" << std::flush;
```
Comment (willkill07) [inline python/morpheus/morpheus/_lib/include/morpheus/controllers/monitor_controller.hpp:123]: newline + flush == `std::endl`
```suggestion
            m_stdout_os << std::endl;
```

**Review by willkill07 — COMMENTED** [review]
One small nit; otherwise LGTM

**Review by dagardner-nv — APPROVED** [review]

**Review by willkill07 — APPROVED** [review]
